apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-pod
  name: hello-pod
spec:
  containers:
  - image: nginx
    name: hello-pod
    resources: 
      requests:
        memory: "32Mi"
        cpu: "125m"
      limits:
        memory: "64Mi"
        cpu: "250m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
