apiVersion: v1
kind: Pod
metadata:
  name: candy-service
spec:
  serviceAccountName: candy-svc
  securityContext:
     fsGroup: 2000
  containers:
  - name: candy-service
    image: linuxacademycontent/candy-service:1
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-password
          key: password
    volumeMounts:
    - name: config-volume
      mountPath: /etc/candy-service
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: config-volume
      configMap:
         name: candy-service-config