apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sunny
  name: sun-srv
  namespace: sun
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9999
  selector:
    app: sunny
status:
  loadBalancer: {}
