apiVersion: v1
kind: Pod
metadata:
  name: my-pvc-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    volumeMounts:
    - name: my-storage
      mountPath: "/mnt/storage" 
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
