apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sec-nginx
  name: sec-nginx
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    name: sec-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
