apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp-bsh
  name: tmp-bsh
  namespace: k8s-challenge-2-a
spec:
  containers:
  - image: cosmintitei/bash-curl
    imagePullPolicy: IfNotPresent
    name: tmp-bsh
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
