apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp2
  name: tmp2
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: tmp2
    volumeMounts:
    - name: tmp-volume
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: tmp-volume
    emptyDir: {}
status: {}

