apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp3
  name: tmp3
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: tmp3
    volumeMounts:
    - name: pvc-volume
      mountPath: /etc/foo
    resources: {}
  nodeSelector:
    test: test
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: mypvc
status: {}
