apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox-complete
spec:
  parallelism: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello;sleep 30; echo world
        image: busybox
        name: busybox-complete
        resources: {}
      restartPolicy: OnFailure
status: {}
