apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-busy-box
  name: my-busy-box
spec:
  containers:
  - command:
    - env
    image: busybox
    name: my-busy-box
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
