apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-multi
  name: nginx-multi
spec:
  containers:
  - image: nginx
    name: nginx-multi
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-volume
  - image: busybox
    name: busybox
    args:
    - wget
    - -O
    - /work-dir/index.html 
    - http://neverssl.com/online
    #command: ['wget', '-O', '//work-dir/index.html http://neverssl.com/online']
    volumeMounts:
    - mountPath: /work-dir
      name: my-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: my-volume
      emptyDir: {}
status: {}
