apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp
  name: tmp
spec:
  containers:
  - env:
    - name: var1
      value: var1
    image: nginx
    name: tmp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
