apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tmp2
  name: tmp2
spec:
  containers:
  - args:
    - /bin/bash
    - -c
    - hello;sleep3600
    image: busybox
    name: busybox1
  - args:
    - /bin/bash
    - -c
    - hello;sleep 3600
    image: busybox
    name: buysbox2
