# apiVersion: v1
# kind: Pod
# metadata:
#   name: testing-busybox
# spec:
#   containers:
#   - image: busybox
#     name: busybox
#     command: ['wget']
#     args: ['-O', '/work-dir/index.html http://neverssl.com/online']
#     volumeMounts:
#     - mountPath: /work-dir
#       name: my-volume
#   dnsPolicy: ClusterFirst
#   restartPolicy: Always
#   volumes:
#     - name: my-volume
#       emptyDir: {}
# status: {}
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testing
  name: testing
spec:
  containers:
  - args:
    - wget
    - -O
    - index.html
    - http://neverssl.com/online
    image: busybox
    name: testing
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
