apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp
  name: tmp
spec:
  containers:
  - command:
    - echo hello;sleep 3600
    image: busybox
    name: tmp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
