apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"role":"ws"},"name":"hitch","namespace":"gem"},"spec":{"containers":[{"image":"ninx:1.15.9","name":"nginx"}]}}
  creationTimestamp: "2021-11-29T00:52:12Z"
  labels:
    role: ws
  name: hitch
  namespace: gem
  resourceVersion: "5611"
  selfLink: /api/v1/namespaces/gem/pods/hitch
  uid: 96fccfb1-50ae-11ec-9b93-0220639176b7
spec:
  containers:
  - image: nginx:1.15.9
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lcmqc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-1-102
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-lcmqc
    secret:
      defaultMode: 420
      secretName: default-token-lcmqc
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-11-29T00:52:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-11-29T00:52:21Z"
    message: 'containers with unready status: [nginx]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-11-29T00:52:21Z"
    message: 'containers with unready status: [nginx]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-11-29T00:52:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: ninx:1.15.9
    imageID: ""
    lastState: {}
    name: nginx
    ready: false
    restartCount: 0
    state:
      waiting:
        message: Back-off pulling image "ninx:1.15.9"
        reason: ImagePullBackOff
  hostIP: 10.0.1.102
  phase: Pending
  podIP: 10.244.1.7
  qosClass: BestEffort
  startTime: "2021-11-29T00:52:21Z"