apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: another-nginx
  name: another-nginx
spec:
  containers:
  - image: nginx
    name: another-nginx
    envFrom: 
    - configMapRef:
        name: anotherone
        #valueFrom:
         # configMapKeyRef:
          #  name: anotherone
           # key: var6
     # - name: VAR7
      #  valueFrom:
       #   configMapKeyRef:
        #    name: anotherone
         #   key: var7
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
