apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vol-nginx
  name: vol-nginx
spec:
  containers:
  - image: nginx
    name: vol-nginx
    resources: {}
    volumeMounts:
    - name: config-volume
      mountPath: /etc/lala
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        name: cmvolume
status: {}
