apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"customer-data-svc","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"customer-data"}}}
  creationTimestamp: "2021-11-28T02:44:39Z"
  name: customer-data-svc
  namespace: default
  resourceVersion: "643"
  selfLink: /api/v1/namespaces/default/services/customer-data-svc
  uid: 21dc5240-4ff5-11ec-94b1-02df30a05dab
spec:
  clusterIP: 10.108.186.32
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: customer-data
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}