apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"inventory-svc","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"inventory"}}}
  creationTimestamp: "2021-11-28T02:44:36Z"
  name: inventory-svc
  namespace: default
  resourceVersion: "618"
  selfLink: /api/v1/namespaces/default/services/inventory-svc
  uid: 20015fe5-4ff5-11ec-94b1-02df30a05dab
spec:
  clusterIP: 10.110.107.112
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: inventory
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}