apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.244.1.5/32
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"web-gateway"},"name":"web-gateway","namespace":"default"},"spec":{"containers":[{"command":["sh","-c","while true; do sleep 3600; done"],"image":"radial/busyboxplus:curl","name":"busybox"}]}}
  creationTimestamp: "2021-11-28T02:44:32Z"
  labels:
    app: web-gateway
    customer-data-access: "true"
    inventory-access: "true"
  name: web-gateway
  namespace: default
  resourceVersion: "1893"
  selfLink: /api/v1/namespaces/default/pods/web-gateway
  uid: 1df2ad2e-4ff5-11ec-94b1-02df30a05dab
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do sleep 3600; done
    image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7xcld
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-1-102
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-7xcld
    secret:
      defaultMode: 420
      secretName: default-token-7xcld
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-11-28T02:46:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-11-28T02:47:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-11-28T02:47:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-11-28T02:46:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://121591bf8c000cf86df1f1f65d69972329e8f51f4616ef2510bb3e3b3462dc6c
    image: radial/busyboxplus:curl
    imageID: docker-pullable://radial/busyboxplus@sha256:a68c05ab1112fd90ad7b14985a48520e9d26dbbe00cb9c09aa79fdc0ef46b372
    lastState: {}
    name: busybox
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2021-11-28T02:47:14Z"
  hostIP: 10.0.1.102
  phase: Running
  podIP: 10.244.1.5
  qosClass: BestEffort
  startTime: "2021-11-28T02:46:39Z"