apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: svc-account-nginx
  name: svc-account-nginx
spec:
  serviceAccountName: myuser
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: svc-account-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
