apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: res-nginx
  name: res-nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: res-nginx
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
