apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-nginx
  name: secret-nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: secret-nginx
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
