apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-nginx
  name: secret-nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: secret-nginx
    volumeMounts:
    - name: foo
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: foo
    secret:
      secretName: mysecret2
status: {}
